# Generated by Django 5.2.17 on 2026-09-23 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "client_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("secret_hash", models.CharField(editable=False, max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("scopes", models.JSONField(default=list)),
                ("ip_allowlist", models.JSONField(blank=True, default=list)),
                ("last_used_at", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rooms.meetingconfigpreset",
                    ),
                ),
            ],
        ),
    ]
