# Generated by Django 5.2.17 on 2026-09-23 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationclient",
            name="token_version",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
