# Generated by Django 5.2.17 on 2026-09-23 11:11

import apps.rooms.configuration
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingConfigPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        validators=[apps.rooms.configuration.validate_config],
                    ),
                ),
                ("is_system_default", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_system_default", True)),
                        fields=("is_system_default",),
                        name="one_system_preset",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("username", models.CharField(max_length=254, unique=True)),
                ("encrypted_password", models.TextField(editable=False)),
                (
                    "credential_version",
                    models.PositiveIntegerField(default=1, editable=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=100)),
                (
                    "max_concurrent_bookings",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "provider_active_meeting_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "default_meeting_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[apps.rooms.configuration.validate_config],
                    ),
                ),
                ("last_auth_at", models.DateTimeField(editable=False, null=True)),
                ("last_auth_success", models.BooleanField(editable=False, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "public_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_concurrent_bookings", 1)),
                        name="single_booking_per_room",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("provider_active_meeting_limit__isnull", True),
                            ("provider_active_meeting_limit__gt", 0),
                            _connector="OR",
                        ),
                        name="positive_provider_limit",
                    ),
                ],
            },
        ),
    ]
