# Generated by Django 5.2.17 on 2026-09-23 11:11

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0000_btree_gist"),
        ("integrations", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_class_id", models.CharField(db_index=True, max_length=160)),
                ("teacher_id", models.CharField(db_index=True, max_length=160)),
                ("teacher_name", models.CharField(max_length=200)),
                (
                    "subject_id",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("subject_name", models.CharField(blank=True, max_length=200)),
                ("batch_id", models.CharField(db_index=True, max_length=160)),
                ("batch_name", models.CharField(max_length=200)),
                ("meeting_title", models.CharField(max_length=250)),
                ("class_date", models.DateField(db_index=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("SCHEDULED", "Scheduled"), ("INSTANT", "Instant")],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("start_at", models.DateTimeField(db_index=True, null=True)),
                ("end_at", models.DateTimeField(db_index=True, null=True)),
                (
                    "reservation",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True),
                ),
                ("reservation_active", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(default="CONVAY", editable=False, max_length=16),
                ),
                (
                    "provider_meeting_type",
                    models.CharField(
                        choices=[("INSTANT", "Instant"), ("SCHEDULED", "Scheduled")],
                        default="INSTANT",
                        max_length=16,
                    ),
                ),
                (
                    "provision_strategy",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("JIT", "Jit"),
                            ("MANUAL", "Manual"),
                        ],
                        default="IMMEDIATE",
                        max_length=16,
                    ),
                ),
                (
                    "provider_calendar_id",
                    models.CharField(db_index=True, max_length=200, null=True),
                ),
                ("provider_unique_id", models.CharField(max_length=200, null=True)),
                ("provider_panel_address", models.URLField(max_length=2000, null=True)),
                (
                    "encrypted_provider_start_url",
                    models.TextField(editable=False, null=True),
                ),
                (
                    "encrypted_provider_payload",
                    models.TextField(editable=False, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("RESERVED", "Reserved"),
                            ("PROVISIONING", "Provisioning"),
                            ("READY", "Ready"),
                            ("LIVE", "Live"),
                            ("ENDED", "Ended"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                            ("PROVIDER_STATE_UNKNOWN", "Provider State Unknown"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("provider_created_at", models.DateTimeField(null=True)),
                ("last_provider_error", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(null=True)),
                (
                    "integration_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrations.integrationclient",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rooms.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("operation", models.CharField(max_length=200)),
                ("payload_hash", models.CharField(max_length=64)),
                ("encrypted_result", models.TextField(editable=False, null=True)),
                ("response_status", models.PositiveSmallIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integrationclient",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="meetings.meeting",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("reservation_active", True)),
                expressions=[("room", "="), ("reservation", "&&")],
                name="exclude_overlapping_room_reservations",
            ),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reservation_active", False),
                    models.Q(
                        ("room__isnull", False),
                        ("reservation__isnull", False),
                        ("start_at__isnull", False),
                        ("end_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="active_reservation_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_at__isnull", True), ("start_at__isnull", True)),
                    ("end_at__gt", models.F("start_at")),
                    _connector="OR",
                ),
                name="positive_meeting_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("client", "key"), name="unique_client_idempotency_key"
            ),
        ),
    ]
