# Generated by Django 5.2.17 on 2026-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_reservation_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='provider_panel_address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RESERVED', 'Reserved'), ('PROVISIONING', 'Provisioning'), ('READY', 'Ready'), ('LIVE', 'Live'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('PROVIDER_RESPONSE_INVALID', 'Provider Response Invalid'), ('PROVIDER_STATE_UNKNOWN', 'Provider State Unknown')], db_index=True, default='DRAFT', max_length=32),
        ),
    ]
