# Generated by Django 5.2.17 on 2026-09-24 09:25

from django.db import migrations, models


def preserve_historical_duplicates(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    duplicate_groups = (
        Meeting.objects.values("integration_client_id", "external_class_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    status_rank = {
        "LIVE": 9,
        "READY": 8,
        "PROVIDER_RESPONSE_INVALID": 7,
        "PROVIDER_STATE_UNKNOWN": 6,
        "PROVISIONING": 5,
        "RESERVED": 4,
        "DRAFT": 3,
        "FAILED": 2,
        "ENDED": 1,
        "CANCELLED": 0,
    }
    for group in duplicate_groups.iterator():
        meetings = list(
            Meeting.objects.filter(
                integration_client_id=group["integration_client_id"],
                external_class_id=group["external_class_id"],
            )
        )
        meetings.sort(
            key=lambda meeting: (
                bool(meeting.provider_calendar_id),
                status_rank.get(meeting.status, -1),
                bool(meeting.reservation_active),
                -meeting.created_at.timestamp(),
            ),
            reverse=True,
        )
        for duplicate in meetings[1:]:
            suffix = "~legacy-" + duplicate.pk.hex[:8]
            preserved_id = group["external_class_id"][: 160 - len(suffix)] + suffix
            Meeting.objects.filter(pk=duplicate.pk).update(
                external_class_id=preserved_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_integrationclient_token_version"),
        ("meetings", "0003_alter_meeting_provider_panel_address_and_more"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            preserve_historical_duplicates, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.UniqueConstraint(
                fields=("integration_client", "external_class_id"),
                name="unique_client_external_class",
            ),
        ),
    ]
