# Generated by Django 5.2.17 on 2026-10-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_unique_client_external_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RESERVED', 'Reserved'), ('PROVISIONING', 'Provisioning'), ('READY', 'Ready'), ('LIVE', 'Live'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('RETRYABLE_FAILED', 'Retryable Failed'), ('NON_RETRYABLE_FAILED', 'Non Retryable Failed'), ('PROVIDER_RESPONSE_INVALID', 'Provider Response Invalid'), ('PROVIDER_STATE_UNKNOWN', 'Provider State Unknown')], db_index=True, default='DRAFT', max_length=32),
        ),
    ]
